//src/ui/utils/AlertPageUtils/marineAreas.js
export const MARINE_AREAS = [
    /*
    Områdene i denne lista er hentet fra meterologisk institutt.
    https://www.met.no/vaer-og-klima/ekstremvaervarsler-og-andre-farevarsler/varslingsomrader-kyst-og-hav
    */
   
    { id: "A1" },
    { id: "A2" },
    { id: "A3" },
    { id: "A4" },
    { id: "A5" },
    { id: "Amundsen-bassenget" },
    { id: "Aust-Tampen" },
    { id: "B1" },
    { id: "B2" },
    { id: "B3" },
    { id: "B4" },
    { id: "B5" },
    { id: "Bankane i Wandelhavet" },
    { id: "Bankane nord for Svalbard" },
    { id: "Bankane utanfor Troms" },
    { id: "C2" },
    { id: "C3" },
    { id: "C4" },
    { id: "C5" },
    { id: "D2" },
    { id: "D3" },
    { id: "Djupe D4" },
    { id: "Djupe E4" },
    { id: "Djupe Wandelhav" },
    { id: "E2" },
    { id: "E3" },
    { id: "F2" },
    { id: "F3" },
    { id: "Finnmarkskysten og deler av Nord-Troms" },
    { id: "Fisker" },
    { id: "Fladen" },
    { id: "Frøyabanken" },
    { id: "Gakkelryggen" },
    { id: "Haltenbanken" },
    { id: "Hjelmsøybanken" },
    { id: "Indre Skagerrak" },
    { id: "Kildinbanken" },
    { id: "Lena-djupet" },
    { id: "Litke djupet" },
    { id: "Nansen-bassenget" },
    { id: "Nordkappbanken" },
    { id: "Nordlege Belgicabank" },
    { id: "Røstbanken" },
    { id: "Sklinnabanken" },
    { id: "Storegga" },
    { id: "Tromsøflaket" },
    { id: "Trænabanken" },
    { id: "Utsira nord" },
    { id: "Utsira sør" },
    { id: "Vesterålsbanken" },
    { id: "Viking" },
    { id: "Yermak-platået" },
    { id: "Ytre Skagerrak" },
    { id: "Ytre Vestfjorden" }
];