//src/ui/utils/MapUtils/Zoom/ZoomConfig.js
export const MIN_ZOOM = 1.7;
export const MAX_ZOOM = 14;

export const ZOOM_LEVELS = {
	STREET: MAX_ZOOM,
	NEIGHBOURHOOD: 12,
	MUNICIPALITY: 10,
	LOCAL_REGION: 9,
	COUNTY: 8,
	SUBREGION: 7,
	REGION: 6,
	SMALL_COUNTRY: 5,
	COUNTRY: 4,
	CONTINENT: 3,
	MAJOR_LANDFORM: MIN_ZOOM,	
};